version: "3.8"
services:
  sqldata:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: garageflow-sqldata
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=StrongPassword123!
  app:
    build:
      context: .
      dockerfile: api/GarageFlow/Dockerfile
    ports:
      - "8081:8080"
    depends_on:
      - sqldata
    environment:
      AppSettings__ConnectionStrings__DefaultConnection: "Server=sqldata;Database=GarageFlowDb;User Id=sa;Password=StrongPassword123!;TrustServerCertificate=True"
