# Set the base image
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build-env

# Set the working directory
WORKDIR /app/api/GarageFlow

# Copy the .csproj and restore dependencies
COPY api/GarageFlow/*.csproj ./
RUN dotnet restore

# Copy the entire project and build
COPY api/GarageFlow/ ./
RUN dotnet publish -c Release -o out

# Build the runtime image
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app/api/GarageFlow
COPY --from=build-env /app/api/GarageFlow/out .

# Copy the appsettings.json file
COPY api/GarageFlow/appsettings.json .

# Set the entry point for the container
ENTRYPOINT ["dotnet", "GarageFlow.dll"]